== SSP Attributes

[[SSP-attributes]]

This chapter introduces and describes the list of SSP attributes. Each attribute is introduced with a attribute description and an indication of the attribute obligation based on the Level, i.e., whether the attribute is mandatory, recommended, or optional for a specific Level of a simulation task, and whether the attribute can be instantiated multiple times or not. To enhance the understanding of an attribute, some value examples and, if applicable, additional explanations or rationales for the attribute are provided .

The attributes are organized by the following attribute groups:

* Administrative data

* Objectives

* Requirements

* Design data

* Implementation

* Execution

* Evaluation

* Fulfillment

=== 2.1 Administration

==== 2.1.1 Overall product name

Attribute description:: The Overall product name is the unique master name of the overall product within the company's project management IT infrastructure, whose development or validation requires the respective simulation.
Obligation and Level:: L1 Rec.
Can have multiple values:: Yes
Value examples:: carZZ, aeroplaneTT
Additional explanation and rationale:: Providing the Overall product name attribute makes it easier to track and trace the impact of a simulation result on the overall product for which the simulation is initially being requested and executed. "Overall product? can also refer to a customer's product if a company develops and simulates a relevant product as a system or component specifically for a customer product.

==== 2.1.2 Overall product version

Attribute description:: The Overall product version is a human readable version designation for the overall product.
Obligation and Level:: L1 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The Overall product version attribute is essential information that helps keep track of which overall product version the simulation task was generated for.

==== 2.1.3 Overall product identifier

Attribute description:: The Overall product identifier is the unique master ID of the overall product within the company's project management IT infrastructure, whose development or validation requires the respective simulation. If the company has a versioning mechanism for products in the project management IT infrastructure, the version ID is included in the identifier so that the product can be referenced with version accuracy.
Obligation and Level:: L1 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The (version accurate) Overall product identifier attribute is essential information needed to facilitate automated traceability to the overall product for which the simulation is initially requested and executed. "Overall product? can also refer to a customer's product if a company develops and simulates a relevant product as a system or component specifically for a customer product.

==== 2.1.4 Overall product URL

Attribute description:: The Overall product URL is an alternate way to identify the overall product. All information given to the overall product identifier attribute apply here.
Obligation and Level:: L1 Opt.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: All of the information provided for the Overall product Identifier attribute applies here as well.

==== 2.1.5 Overall product full name

Attribute description:: The Overall product full name is the commonly known name of the overall product, whose development or validation requires the respective simulation.
Obligation and Level:: L1 Opt.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Overall product full name attribute with potentially relevant details helps quickly understand the overall product context for which the simulation is initially requested and executed. "Overall product? can also refer to a customer's product if a company develops and simulates a relevant product as a system or component specifically for a customer product.

==== 2.1.6 Specific product name

Attribute description:: The Specific product name is the unique master name of the specific product within the company's project management IT infrastructure, whose development or validation requires the respective simulation.
Obligation and Level:: L1 Man.
Can have multiple values:: No
Value examples:: AD-34basic
Additional explanation and rationale:: Providing the Specific product name attribute makes it easier to track and trace the impact of a simulation result on the specific product for which the simulation is initially being requested.

==== 2.1.7 Specific product version

Attribute description:: The Specific product version is a human readable version designation for the specific product.
Obligation and Level:: L1 Rec.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: The Specific product version attribute is essential information that helps keep track of which specific product version the simulation task was generated for.

==== 2.1.8 Specific product identifier

Attribute description:: The specific product identifier is the unique master ID of the specific product within the company's project management IT infrastructure, whose development or validation requires the respective simulation. If the company has a versioning mechanism for products in project management IT infrastructure, the version ID is included in the identifier so that the product can be referenced with version accuracy.
Obligation and Level:: L1 Man.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: The (version accurate) Specific product identifier attribute is essential information needed to facilitate automated traceability to the specific product for which the simulation is initially requested.

==== 2.1.9 Specific product URL

Attribute description:: The Specific product URL is a alternate way to identify the specific product. All information given to the specific product identifier attribute apply here.
Obligation and Level:: L1 Opt.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: All of the information provided for the Specific product Identifier attribute applies here as well.

==== 2.1.10 Specific product full name

Attribute description:: The Specific product full name is the commonly known name of the specific product, whose development or validation requires the respective simulation.
Obligation and Level:: L1 Opt.
Can have multiple values:: No
Value examples:: autonomous driving function based on camera
Additional explanation and rationale:: Providing the Overall product full name with potentially relevant details helps quickly understand the overall product context for which the simulation is initially requested.

==== 2.1.11 Ordering project name

Attribute description:: The Ordering project name is the unique master name of the ordering development project within the company's project management IT infrastructure.
Obligation and Level:: L1 Man.
Can have multiple values:: No
Value examples:: cam34basic
Additional explanation and rationale:: Providing the Ordering project name attribute makes it easier to track and trace the simulation task and the simulation request back to the ordering development project and its engineering context.

==== 2.1.12 Ordering project version

Attribute description:: The Specific product Ordering project version is a human readable version designation for the ordering project.
Obligation and Level:: L1 Rec.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: The Ordering project version attribute is essential information that helps keep track of which order?ng project# version the simulation task was generated for.

==== 2.1.13 Ordering project identifier

Attribute description:: The Ordering project identifier is the unique master ID of the ordering development project within the company's project management IT infrastructure.
Obligation and Level:: L1 Man.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: The Ordering project identifier is essential information needed to facilitate automated traceability of simulation tasks and simulation requests to the ordering development project.

==== 2.1.14 Ordering project URL

Attribute description:: The Ordering project URL is a alternate way to identify the ordering project. All information given to the ordering project identifier attribute apply here.
Obligation and Level:: L1 Opt.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: All of the information provided for the Ordering project Identifier attribute applies here as well.

==== 2.1.15 Ordering project full name

Attribute description:: The Ordering project full name is the commonly known name of the project that requires the respective simulation.
Obligation and Level:: L1 Opt.
Can have multiple values:: No
Value examples:: camera34 for autonomous driving function
Additional explanation and rationale:: Providing the Ordering project full name attribute helps quickly understand the development context from which the simulation is initially requested.

==== 2.1.16 Simulation request name

Attribute description:: The Simulation request name is the unique name of the simulation request within the company's project management IT infrastructure.
Obligation and Level:: L1 Man.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: Providing  the Simulation request name attribute makes it easier to trace back to the simulation request when it is referenced in a simulation task or simulation delivery, for example.

==== 2.1.17 Simulation request version

Attribute description:: The Simulation request version is a human readable version designation for the simulation request.
Obligation and Level:: L1 Rec.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: The Simulation request version attribute is essential information that helps keep track of which received simulation request version the generated simulation task refers to.

==== 2.1.18 Simulation request identifier

Attribute description:: The Simulation request identifier is the unique master ID of the simulation request within the company's project management IT infrastructure.  If the company has a versioning mechanism for simulation requests in the project management IT infrastructure, the version ID is included in the identifier so that the simulation request can be referenced with version accuracy.
Obligation and Level:: L1 Man.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: The (version accurate) Simulation request identifier attribute is essential information to ensure that a simulation executed on request and its results can be uniquely assigned to the simulation request.

==== 2.1.19 Simulation request URL

Attribute description:: The Simulation request URL is a alternate way to identify the simulation request. All information given to the simulation request identifier attribute apply here.
Obligation and Level:: L1 Opt.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: All of the information provided for the Simulation request Identifier attribute applies here as well.

==== 2.1.20 Simulation request full name

Attribute description:: The Simulation request full name is a descriptive name of the simulation request.
Obligation and Level:: L1 Opt.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: Providing the Simulation request full name attribute helps quickly recognize and understand the meaning of a simulation request.

==== 2.1.21 Simulation request creator name

Attribute description:: The Simulation request creator name is the name or other regulatory-compliant valid identifier of the person who initially created the simulation request in the project management IT system.
Obligation and Level:: L4 Opt.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: The Simulation request creator name attribute should automatically be extracted from the project management IT system

==== 2.1.22 Simulation request creation date

Attribute description:: The Simulation request  creation date ist the name oder other regulatory-compliant valid identifier of the person who initially created the simulation request in the project management IT system.
Obligation and Level:: L4 Opt.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: The Simulation request creation date attribute should automatically be extracted from the project management IT system

==== 2.1.23 Simulation task name

Attribute description:: The Simulation task name is the unique name of the simulation task within the originating company's project management IT infrastructure.
Obligation and Level:: L1 Man.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: Providing the Simulation task name attribute  makes it easier to trace back to the simulation task when it is referenced in a simulation delivery.

==== 2.1.24 Simulation task version

Attribute description:: The Simulation task version is a human readable version designation for the simulation task.
Obligation and Level:: L1 Rec.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: The Simulation task version attribute is essential information that helps keep track of which simulation task version a generated simulation delivery refers to.

==== 2.1.25 Simulation task identifier

Attribute description:: The Simulation task identifier is the unique master ID of the simulation task within the  company's project management IT infrastructure.  If the  company has a versioning mechanism for simulation tasks in the project management IT infrastructure, the version ID is included in the identifier so that the simulation task can be referenced with version accuracy.
Obligation and Level:: L1 Man.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: The (version accurate) Simulation task identifier attribute is essential information to ensure that the simulation results generated by the simulation task can be uniquely assigned to the simulation task.

==== 2.1.26 Simulation task URL

Attribute description:: The Simulation task URL is a alternate way to identify the simulation task. All information given to the simulation task identifier attribute apply here.
Obligation and Level:: L1 Opt.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: All of the information provided for the Simulation task Identifier attribute applies here as well.

==== 2.1.27 Simulation task full name

Attribute description:: The Simulation task full name is a descriptive name for the simulation task.
Obligation and Level:: L1 Opt.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: Providing the Simulation task full name attribute helps quickly recognize and understand the meaning of a simulation task.

==== 2.1.28 Simulation task confidentiality level

Attribute description:: The Simulation task confidentiality level is a  classification with respect to the access to contained information.
Obligation and Level:: L1 Rec.
Can have multiple values:: No
Value examples:: CSC-0: public CSC-1: internal CSC-2: confidential CSC-3: strictly confidential
Additional explanation and rationale:: The Simulation task confidentiality level attribute uses a classification system that specifies how confidential the information contained in the classified document is to be treated. Typically, there is a set of rules that specifies what may and may not be done with a document and the information it contains.

==== 2.1.29 Simulation task creator name

Attribute description:: The Simulation task creator name is the name or other regulatory-compliant valid identifier of the person who initially created the simulation task in the project management IT system.
Obligation and Level:: L4 Opt.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: The Simulation task creator name attribute should automatically be extracted from the project management IT system

==== 2.1.30 Simulation task creation date

Attribute description:: The Simulation request creation date is the date the simulation request in the project management IT system was created.
Obligation and Level:: L4 Opt.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: The Simulation task creation date attribute should automatically be extracted from the project management IT system

==== 2.1.31 Predicted simulation start date

Attribute description:: The Predicted simulation start date is the date at which all information will have been provided so that the simulation service can start.
Obligation and Level:: L3 Rec.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: The Predicted simulation start date is meaningful information for the simulation engineers for simulation process planning and team workload planning.

==== 2.1.32 Requested simulation delivery date

Attribute description:: The Requested simulation delivery date is the due date that the simulation results will be appreciated by the ordering person or organization.
Obligation and Level:: L3 Rec.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: Providing a Requested simulation delivery date attribute helps plan the details of a simulation process depending on available organizational and technical resources and the expected process duration.

==== 2.1.33 Requesting person

Attribute description:: The Requesting person is the person who needs the obtained simulation results on a technical level and will work with the results.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Requesting person attribute in combination with the contracting person attribute helps streamline communication in the event of questions about the details of the request or a need for technical clarification. Which requesting person's information is actually provided depends on negotiations and regulations.

==== 2.1.34 Requesting entity

Attribute description:: The Requesting entity is the department or external company that needs the obtained simulation results on a technical level and will work with the results.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Requesting entity attribute in combination with the contracting entity attribute helps streamline communication in the event of questions about the details of the request or a need for technical clarification. What information about the requesting entity's information is actually provided depends on negotiations and regulations.

==== 2.1.35 Contracting person

Attribute description:: The Contracting person is the person who accepts the simulation request to provide a simulation service.
Obligation and Level:: L3 Rec.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: Providing the Contracting person attribute, in combination with the requesting person attribute helps streamline communication in the event of administrative questions about the details of the request or a need for administrative clarification. Which contracting person's information is actually provided depends on negotiations and regulations.

==== 2.1.36 Contracting entity

Attribute description:: The Contracting entity is the department or external company who accepts the simulation request to provide a simulation service.
Obligation and Level:: L3 Rec.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: Providing the Contracting entity attribute in combination with the requesting entity attribute helps streamline communication in the event of questions about the details of the request or a need for technical clarification. What information about the contracting entity's information is actually provided depends on negotiations and regulations.

=== 2.2 Objectives

==== 2.2.1 Name of Item under test

Attribute description:: The Item under test specifies the product, system, component, or software, etc.  that is subject of a simulation being requested by a simulation request or performed by a simulation task.
Obligation and Level:: L1 Man.
Can have multiple values:: Yes
Value examples:: camera34, camera34-A-sampleV23
Additional explanation and rationale:: Providing the Item under test attribute helps clarifying the subject of simulation.

==== 2.2.2 Item under Test version

Attribute description:: The Item under Test version is a human readable version designation for the overall product.
Obligation and Level:: L1 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The Item under Test version attribute is essential information that helps keep track of which overall product version the simulation task was generated for.

==== 2.2.3 ID of Item under test

Attribute description:: The Item under Test identifier is the unique master ID of the overall product within the company's project management IT infrastructure, whose development or validation requires the respective simulation. If the company has a versioning mechanism for products in the project management IT infrastructure, the version ID is included in the identifier so that the product can be referenced with version accuracy.
Obligation and Level:: L1 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The (version accurate) Item under Test identifier attribute is essential information needed to facilitate automated traceability to the overall product for which the simulation is initially requested and executed. "Overall product? can also refer to a customer's product if a company develops and simulates a relevant product as a system or component specifically for a customer product.

==== 2.2.4 Item under Test URL

Attribute description:: The Item under Test URL is an alternate way to identify the overall product. All information given to the overall product identifier attribute apply here.
Obligation and Level:: L1 Opt.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: All of the information provided for the Item under Test Identifier attribute applies here as well.

==== 2.2.5 Item under Test full name

Attribute description:: The Item under Test full name is the commonly known name of the overall product, whose development or validation requires the respective simulation.
Obligation and Level:: L1 Opt.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Item under Test full name attribute with potentially relevant details helps quickly understand the overall product context for which the simulation is initially requested and executed. "Overall product? can also refer to a customer's product if a company develops and simulates a relevant product as a system or component specifically for a customer product.

==== 2.2.6 Higher level engineering task

Attribute description:: The Higher level engineering task is a higher level engineering task that sets the context of the specific engineering task.
Obligation and Level:: L3 Rec.
Can have multiple values:: No
Value examples:: (e.g. development of an AD driving function based on camera signals)
Additional explanation and rationale:: The Higher level engineering task attribute in combination with the Specific engineering task attribute supports understanding the context in witch the simulation is placed.

==== 2.2.7 Specific engineering task

Attribute description:: The Specific engineering task is the engineering that directly benefits from the simulation results.
Obligation and Level:: L1 Rec.
Can have multiple values:: No
Value examples:: (e.g. detection of critical occlusions when turning right with pedestrians)
Additional explanation and rationale:: The Specific engineering task attribute in combination with the Higher level engineering task attribute supports understanding the context in witch the simulation is placed.

==== 2.2.8 Simulation task target

Attribute description:: The Simulation task target represents the engineering question that is to be answered by the simulation task.
Obligation and Level:: L1 Man.
Can have multiple values:: Yes
Value examples:: (e.g. assessment of the camera resolution by simulation)
Additional explanation and rationale:: Providing the Simulation task target attribute helps keep the focus on the target and to ensures that the entire simulation task is streamlined to the target.

==== 2.2.9 Simulation objective

Attribute description:: The Simulation objective describes, in numerical notation, exactly what is to be determined, confirmed, or refuted by a simulation.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: (e.g. the distance between vehicle and pedestrian must be higher than 1.5m)
Additional explanation and rationale:: Providing the Simulation objectives attribute is an important input for the development of the test cases of a simulation. By specifying the simulation objectives numerically, the simulation results can be mathematically compared to the objectives.

==== 2.2.10 Quality criterion

Attribute description:: A Quality criterion is a quality requirement that must be met during the simulation, particularly given the importance of the decision to be made.
Obligation and Level:: L3 Man
Can have multiple values:: Yes
Value examples:: companyZ simulation quality assessment
Additional explanation and rationale:: The Quality criterion attribute facilitate the configuration of the simulation setup.

==== 2.2.11 Verification criterion

Attribute description:: A Verification criterion is a quality requirement that must be met during the simulation in order to verify that the simulation results align with the specified objectives of the simulation task.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Verification criterion attribute helps to align with the specific engineering task and to facilitate the simulation setup by providing clear instructions.

==== 2.2.12 Validation criterion

Attribute description:: A Validation criterion is a quality requirement that must be met during the simulation in order to validate that the simulation results align with the needs of the specific engineering task that requested the simulation.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The Validation criterion attribute helps  to guarantee that the simulation objectives and targets align with the specific engineering requirements and to define the simulation setup.

==== 2.2.13 Analysis phase verification result

Attribute description:: The Analysis phase verification result is the conclusion of the analysis phase closing verification.
Obligation and Level:: L3 Rec.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: The Analysis phase verification result attribute serves to confirm that the analysis of the engineering task has been properly performed. This could be a link to a document.

=== 2.3 Requirements

==== 2.3.1 Model purpose and objectives

Attribute description:: The Model purpose and objectives are indicating, based on the simulation purpose and objectives, individual model purpose and objectives.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: specification of camera resolution for Automated driving function at object-list level
Additional explanation and rationale:: The Model purpose and objectives attribute, in alignment with the simulation purpose and objectives, facilitates the specification of individual simulation models and parameters.

==== 2.3.2 Modeled entity

Attribute description:: The Modeled entity is the real-world entity that is to be modeled.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: camera34-A-sampleV23
Additional explanation and rationale:: Providing the Modeled entity attribute enables specification of individual simulation models and parameters. This could not only comprise the item under test, but all additional entities modeled needed to conduct the simulation.

==== 2.3.3 Required modeled effect

Attribute description:: The Required modeled effect is a real-world physical effect that is to be considered in the modeling.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: resolution of camera
Additional explanation and rationale:: The Required modeled effect is a real-world physical effect that should be considered in modeling.

==== 2.3.4 Further model requirements

Attribute description:: The Further model requirements is additional requirements placed on a model, including things that explicitly shall / are not be considered in the model.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The Further model requirements shall be considered in the same liability as the required modeled effects. This may not yet be available at the start of the simulation task. The attribute could therefore be omitted. It should be present once the simulation task has been completed.

==== 2.3.5 Simulation model confidentiality level

Attribute description:: The Simulation model confidentiality level is a  classification with respect to the access to classified information.
Obligation and Level:: L2 Rec.
Can have multiple values:: No
Value examples:: CSC-0: public CSC-1: internal CSC-2: confidential CSC-3: strictly confidential
Additional explanation and rationale:: The Simulation model confidentiality level attribute uses a classification system that specifies how confidential the information contained in the classified document is to be treated. Typically, there is a set of rules that specifies what may and may not be done with a document and the information it contains.

==== 2.3.6 Model quality requirement

Attribute description:: A Model quality requirement is a requirement placed on a simulation model.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Model quality requirement attribute helps specify the implementation of simulation models.

==== 2.3.7 Entity parameters

Attribute description:: The Entity parameters reference provided parameters of the entity to be modeled.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: # data sheet of camera # material database
Additional explanation and rationale:: Providing the Entity parameter attribute is essential input information for the parameterization.

==== 2.3.8 Value distribution function

Attribute description:: The Value distribution function (value deviation) specifies the probability of deviations certain value.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The Value distribution function attribute serves for ensuring that the simulation results are robust against little value deviation in a real world situation (required tolerances uncertainties).

==== 2.3.9 Parameter confidentiality level

Attribute description:: The Parameter confidentiality level is a  classification with respect to the access to classified information.
Obligation and Level:: L2 Rec.
Can have multiple values:: No
Value examples:: CSC-0: public CSC-1: internal CSC-2: confidential CSC-3: strictly confidential
Additional explanation and rationale:: The Parameter confidentiality level attribute uses a classification system that specifies how confidential the information contained in the classified document is to be treated. Typically, there is a set of rules that specifies what may and may not be done with a document and the information it contains.

==== 2.3.10 Parameter quality requirement

Attribute description:: A Parameter quality requirement is a requirement placed on (a set of) parameters.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Parameter quality requirements in requirements phase attribute helps specify the implementation of parameters.

==== 2.3.11 Simulation environment requirement

Attribute description:: A Simulation environment requirement is a requirement placed on the simulation environment.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: # tool for causal modeling and simulation and supporting FMI # FEM
Additional explanation and rationale:: Providing the Simulation environment requirement attribute helps specify the required simulation environment.

==== 2.3.12 Simulation environment quality requirement

Attribute description:: A Simulation environment quality requirement is a requirement placed on the simulation environment.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Simulation environment quality requirement attribute helps specify the required simulation environment.

==== 2.3.13 Simulation integration requirement

Attribute description:: A Simulation integration requirement is a requirement placed on the interaction of the simulation setup elements.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Simulation integration requirement attribute helps specify the required simulation integration, i.e. to specify how all elements of the simulation setup should interact.

==== 2.3.14 Simulation integration quality requirement

Attribute description:: A Simulation integration quality requirement is a requirement that is placed on the simulation integration.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Simulation integration quality requirement attribute helps specify the needed simulation integration, i.e., specify how all elements of the simulation setup shall interact.

==== 2.3.15 Test case requirements

Attribute description:: The Test case requirements is the description of the goals and objectives of a test case.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Test case requirements attribute helps specify the implementation of test cases.

==== 2.3.16 Test case quality requirement

Attribute description:: A Test case quality requirement is a requirement that is placed on a test case.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing Test case quality requirement attribute helps specify the implementation of test cases.

==== 2.3.17 Quality assurance requirements

Attribute description:: A Quality assurance requirements is a requirements that is placed on the quality assurance in the requirements phase.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Quality assurance requirements attribute helps understand the quality assurance measures made in the requirements phase. The attribute contains the derivation or decomposition of the quality criteria specified in the objectives section.

==== 2.3.18 Requirements phase verification result

Attribute description:: The Requirements verification result is the result of the verification activity  in the requirements phase.
Obligation and Level:: L3 Rec.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: Providing a Requirements verification result attribute helps recognize the quality status of the requirements phase results. This attribute can contain a link to a verification report.

=== 2.4 Design

==== 2.4.1 Model design specification

Attribute description:: A Model design specification is the definition of how models are to be implemented, including model approaches, interfaces model structure, etc.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The Model design specification attribute provides the base for the model implementation. Typically, the attribute contains a link to the appropriate document or the model name and version which should be used.

==== 2.4.2 Model quality requirement

Attribute description:: A Model quality requirement is a requirement that is placed on a simulation model.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Model quality requirement helps to implement simulation models with appropriate and sufficient quality.

==== 2.4.3 Parameter design specification

Attribute description:: A Parameter design specification is the definition of how parameters are to be implemented, including including parameter structures, names, values, tolerances, etc.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: # format  test environment  # links to data sheets, measurements, material data  # specifications on handling tolerances  uncertainties
Additional explanation and rationale:: The Parameter design specification attribute provides the base for the (set of ) parameters implementation. Typically, the attribute contains a link to the appropriate document or the parameter name and version which should be used.

==== 2.4.4 Parameter quality requirement

Attribute description:: A Parameter quality requirement is a requirement that is placed on (a set of) parameters.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Parameter quality requirement attribute helps to implement the (set of) parameters with appropriate and sufficient quality.

==== 2.4.5 Simulation environment design specification

Attribute description:: A Simulation environment design specification is the definition of how simulation environment is to be implemented or which tool and version should be used
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The Simulation environment design specification attribute provides the base for the  Simulation environment implementation. Typically the attribute contains a link to the appropriate document or the tool name and version which should be used

==== 2.4.6 Simulation environment quality requirement

Attribute description:: A Simulation environment quality requirement is a requirement that is placed on a simulation environment.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Simulation environment quality requirement attribute helps to implement the simulation environment with appropriate and sufficient quality or the chosen tool has to fulfill.

==== 2.4.7 Simulation integration design specification

Attribute description:: A Simulation integration design specification is the definition of how simulation components are to be integrated
Obligation and Level:: L3 Rec.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: The Simulation integration design specification attribute provides the base for the  Simulation integration implementation. Typically the attribute contains a link to the appropriate document.

==== 2.4.8 Simulation integration quality requirement

Attribute description:: A Simulation integration quality requirement is a requirement that is placed on a simulation environment.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Simulation integration quality requirement attribute helps to implement the simulation environment with appropriate and sufficient quality. This includes all interactions of simulation setup elements.

==== 2.4.9 Test case design specification

Attribute description:: A Test case design specification is the definition of how test cases are to be implemented.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: i.e. formats  structure  clarification
Additional explanation and rationale:: The Test case design specification are the base for test cases.

==== 2.4.10 Test case quality requirement

Attribute description:: A Test case quality requirement is a requirement that is placed on a test cases.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Test case quality requirement helps to implement test cases with appropriate and sufficient quality.

==== 2.4.11 Design phase quality assurance

Attribute description:: A Design phase quality assurance describe a quality assurance measure in the design phase.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Design phase quality assurance helps understanding the quality assurance measures made in the design phase.

==== 2.4.12 Design phase verification result

Attribute description:: The Design verification result is the result of the verification activity  in the design phase.
Obligation and Level:: L3 Rec.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: Providing the Design verification result helps to recognize the quality status of the requirements phase results.  This attribute can contain a link to a verification report.

=== 2.5 Implementation

==== 2.5.1 Simulation model name

Attribute description:: The Simulation model name is the given name for the implemented simulation model within the company's project management IT infrastructure.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Simulation model name attribute makes it easier to track and trace the simulation models implemented.

==== 2.5.2 Simulation model version

Attribute description:: The Simulation model version is a human readable version designation for the simulation model.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The Simulation model version attribute is essential information that helps keep track of which received simulation model version the generated a certain simulation task refers to.

==== 2.5.3 Simulation model identifier

Attribute description:: The Simulation model identifier is the unique master ID of the simulation model within the company's project management IT infrastructure.  If the company has a versioning mechanism for simulation models in the project management IT infrastructure, the version ID is included in the identifier so that the simulation model can be referenced with version accuracy.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The (version accurate) Simulation model identifier attribute is essential information needed to facilitate automated traceability of simulation tasks and simulation requests to the simulation models implemented.

==== 2.5.4 Simulation model URL

Attribute description:: The Simulation model URL is a alternate way to identify the simulation model. All information given to the simulation model identifier attribute apply here.
Obligation and Level:: L2 Opt.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: All of the information provided for the Simulation model Identifier attribute applies here as well.

==== 2.5.5 Simulation model full name

Attribute description:: The Simulation model full name is a descriptive name for the simulation model.
Obligation and Level:: L2 Opt.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Simulation model full name attribute helps quickly recognize and understand the meaning of a simulation model.

==== 2.5.6 Simulation model confidentiality level

Attribute description:: The Simulation model confidentiality level is a  classification with respect to the access to classified information.
Obligation and Level:: L2 Rec.
Can have multiple values:: No
Value examples:: CSC-0: public CSC-1: internal CSC-2: confidential CSC-3: strictly confidential
Additional explanation and rationale:: The Simulation model confidentiality level attribute uses a classification system that specifies how confidential the information contained in the classified document is to be treated. Typically, there is a set of rules that specifies what may and may not be done with a document and the information it contains.

==== 2.5.7 Simulation model quality

Attribute description:: The Simulation model quality is a statement of any kind that describes the model quality actually achieved by implementation.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Simulation model quality attribute helps to assess the quality of a model.

==== 2.5.8 

Attribute description:: 
Obligation and Level:: 
Can have multiple values:: 
Value examples:: 
Additional explanation and rationale:: 

==== 2.5.9 Parameter name

Attribute description:: The Parameter name is the given name for the implemented (set of) parameters within the company's project management IT infrastructure.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the parameter name attribute makes it easier to track and trace the (set of) parameters implemented.

==== 2.5.10 Parameter version

Attribute description:: The Parameter version is a parameter or parameter set version.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The combination of Parameter name and Parameter version shall be unique.

==== 2.5.11 Parameter identifier

Attribute description:: The Parameter identifier is the unique master ID of the parameter within the company's project management IT infrastructure.  If the company has a versioning mechanism for parameters in the project management IT infrastructure, the version ID is included in the identifier so that the parameters can be referenced with version accuracy.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The (version accurate) Parameter identifier attribute is essential information needed to facilitate automated traceability of simulation tasks and simulation requests to the parameters implemented.

==== 2.5.12 Parameter URL

Attribute description:: The Parameter URL is a alternate way to identify the parameter. All information given to the parameter identifier attribute apply here.
Obligation and Level:: L2 Opt.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: All of the information provided for the Parameter identifier attribute applies here as well.

==== 2.5.13 Parameter full name

Attribute description:: The Parameter full name is a descriptive name for the parameter.
Obligation and Level:: L2 Opt.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Parameter full name attribute helps quickly recognize and understand the meaning of a parameter.

==== 2.5.14 Parameter confidentiality level

Attribute description:: The Parameter confidentiality level is a  classification with respect to the access to classified information.
Obligation and Level:: L2 Rec.
Can have multiple values:: No
Value examples:: CSC-0: public CSC-1: internal CSC-2: confidential CSC-3: strictly confidential
Additional explanation and rationale:: The Parameter confidentiality level attribute uses a classification system that specifies how confidential the information contained in the classified document is to be treated. Typically, there is a set of rules that specifies what may and may not be done with a document and the information it contains.

==== 2.5.15 Parameter quality

Attribute description:: The Parameter quality is a statement of any kind that describes the parameter quality actually achieved by implementation.
Obligation and Level:: L2 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Parameter quality attribute helps to assess the quality of a parameter or a set of parameters.

==== 2.5.16 Simulation environment name

Attribute description:: The Simulation environment name  is the given name for the implemented simulation environment within the company's project management IT infrastructure.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Simulation environment name attribute makes it easier to track and trace the simulation environment implemented.

==== 2.5.17 Simulation environment version

Attribute description:: The Simulation environment version is an implemented simulation environment.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The combination of Simulation environment name and Simulation environment version shall be unique.

==== 2.5.18 Simulation environment identifier

Attribute description:: The Simulation environment identifier is the unique master ID of the simulation environment within the company's project management IT infrastructure.  If the company has a versioning mechanism for simulation environments in the project management IT infrastructure, the version ID is included in the identifier so that the simulation environment can be referenced with version accuracy.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The (version accurate) Simulation environment identifier attribute is essential information needed to facilitate automated traceability of simulation tasks and simulation requests to the simulation environment implemented.

==== 2.5.19 Simulation environment URL

Attribute description:: The Simulation environment URL is a alternate way to identify the simulation environment . All information given to the simulation environment  identifier attribute apply here.
Obligation and Level:: L2 Opt.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: All of the information given for the Simulation environment identifier attribute applies here as well.

==== 2.5.20 Simulation environment full name

Attribute description:: The Simulation environment full name is a descriptive name for the simulation environment.
Obligation and Level:: L2 Opt.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Simulation environment full name attribute helps quickly recognize and understand the meaning of a simulation environment.

==== 2.5.21 Simulation environment quality

Attribute description:: The Simulation environment quality is a statement of any kind that describes the simulation environment quality actually achieved by implementation.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Simulation environment quality attribute helps to assess the quality of a simulation environment.

==== 2.5.22 Test case name

Attribute description:: The Test case name is the given name for the implemented test cases within the company's project management IT infrastructure.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Test case name attribute makes it easier to track and trace the test cases implemented.

==== 2.5.23 Test case version

Attribute description:: The Test case version is a  version of an implemented test case.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The combination of Test case name and Test case version shall be unique.

==== 2.5.24 Test case identifier

Attribute description:: The Test case identifier is the unique master ID of the test case within the company's project management IT infrastructure.  If the company has a versioning mechanism for test cases in the project management IT infrastructure, the version ID is included in the identifier so that the test case can be referenced with version accuracy.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The (version accurate) Test case identifier attribute is essential information needed to facilitate automated traceability of simulation tasks and simulation requests to the test cases implemented.

==== 2.5.25 Test case URL

Attribute description:: The Test case URL is a alternate way to identify the test case. All information given to the test case identifier attribute apply here.
Obligation and Level:: L2 Opt.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: All of the information given for the Test case identifier attribute applies here as well.

==== 2.5.26 Test case full name

Attribute description:: The Test case full name is a descriptive name for the test case.
Obligation and Level:: L2 Opt.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Test case full name attribute helps quickly recognize and understand the meaning of a test case.

==== 2.5.27 Test case confidentiality level

Attribute description:: The Test case confidentiality level is a  classification with respect to the access to classified information.
Obligation and Level:: L2 Rec.
Can have multiple values:: No
Value examples:: CSC-0: public CSC-1: internal CSC-2: confidential CSC-3: strictly confidential
Additional explanation and rationale:: The Test case confidentiality level attribute uses a classification system that specifies how confidential the information contained in the classified document is to be treated. Typically, there is a set of rules that specifies what may and may not be done with a document and the information it contains.

==== 2.5.28 Test case quality

Attribute description:: The Test case quality is a statement of any kind that describes the test case quality actually achieved by implementation.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Test case quality attribute helps to assess the quality of a test case+J38.

==== 2.5.29 Simulation integration name

Attribute description:: The Simulation integration is the given name for the implemented simulation integration within the company's project management IT infrastructure.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Simulation integration name attribute makes it easier to track and trace the simulation integration implemented.

==== 2.5.30 Simulation integration version

Attribute description:: The Simulation integration version is an implemented simulation integration.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The combination of simulation integration name and simulation integration version shall be unique.

==== 2.5.31 Simulation integration identifier

Attribute description:: The Simulation integration identifier is the unique master ID of the simulation integration within the company's project management IT infrastructure.  If the company has a versioning mechanism for simulation integrations in the project management IT infrastructure, the version ID is included in the identifier so that the simulation integration can be referenced with version accuracy.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The (version accurate) Simulation integration identifier attribute is essential information needed to facilitate automated traceability of simulation tasks and simulation requests to the simulation integration implemented.

==== 2.5.32 Simulation integration URL

Attribute description:: The Simulation integration URL is a alternate way to identify the simulation integration. All information given to the simulation integration identifier attribute apply here.
Obligation and Level:: L2 Opt.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: All of the information given for the Simulation integration identifier attribute applies here as well.

==== 2.5.33 Simulation integration full name

Attribute description:: The Simulation integration full name is a descriptive name for the simulation integration.
Obligation and Level:: L2 Opt.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Simulation integration full name attribute helps quickly recognize and understand the meaning of a simulation integration.

==== 2.5.34 Solver setting

Attribute description:: A Solver setting is a specific parameter that control the behavior of simulation solver tools.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Solver setting attribute helps to complete the simulation setup with recommended settings to control the requested behavior of the solver tool..

==== 2.5.35 Simulation integration quality

Attribute description:: The Simulation integration quality is a statement of any kind that describes the simulation integration quality actually achieved by implementation.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Simulation integration quality attribute helps to assess the quality of a simulation integration.

==== 2.5.36 Implementation quality assurance results

Attribute description:: The Implementation quality assurance results describe the outcome of quality measurements done.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the  Implementation quality assurance results attribute helps to recognize and understand the base of the implementation quality verdict.  This attribute can contain a link to the results or quality assurance report.

==== 2.5.37 Implementation quality verdict

Attribute description:: The Implementation quality verdict is the yes or no resp. passed or failed decision to the final implementation quality assurance.
Obligation and Level:: L4 Opt.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: Providing the Implementation quality verdict attribute helps to recognize the quality status of the overall implementation work.  This attribute can contain a link to a signed quality assurance protocol.

=== 2.6 Execution

==== 2.6.1 Execution raw data

Attribute description:: The attribute Execution raw data refers to the data that originally resulted from a simulation run before any digital or manual processing was carried out.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The Execution raw data is usually only stored for further processing for a limited time and discarded as soon as the desired or required relevant simulation results have been extracted from the raw data and processed, e.g. incorporated into design decisions. However, this does not always have to be the case. If raw data is discarded, a link to the raw data would fail.

==== 2.6.2 Used simulation model name

Attribute description:: The Used simulation model name is the given name of a simulation model actually used in simulation execution.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Used simulation model name attribute makes it easier to track and trace the simulation model actually used in the simulation.

==== 2.6.3 Used simulation model version

Attribute description:: The Used simulation model version is the given version identifier of a simulation model actually used in simulation execution.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The Used simulation model version attribute is essential information that helps keep track and trace the simulation model version actually used in the simulation.

==== 2.6.4 Used simulation model identifier

Attribute description:: The Used simulation model identifier is the unique master ID of the used simulation model within the company's project management IT infrastructure. If the company has a versioning mechanism for simulation models in project management IT infrastructure, the version ID is included in the identifier so that the model can be referenced with version accuracy.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The (version accurate) Simulation model identifier attribute is essential information needed to facilitate automated traceability to the used simulation model.

==== 2.6.5 Used simulation model URL

Attribute description:: The Used simulation model URL is a alternate way to identify the used simulation model. All information given to the used simulation model identifier attribute apply here.
Obligation and Level:: L2 Opt.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: All of the information given for the Used simulation model identifier attribute applies here as well.

==== 2.6.6 Used parameter name

Attribute description:: The Used parameter name is the given name of a parameter or parameter set actually used in simulation execution.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the used parameter name attribute makes it easier to track and trace the simulation model actually used in the simulation.

==== 2.6.7 Used parameter version

Attribute description:: The Used parameter version is the given version identifier of a parameter or parameter set actually used in simulation execution.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The Used parameter version attribute is essential information that helps keep track and trace the simulation model version actually used in the simulation.

==== 2.6.8 Used parameter identifier

Attribute description:: The Used parameter identifier is the unique master ID of the used parameter within the company's project management IT infrastructure. If the company has a versioning mechanism for parameters in project management IT infrastructure, the version ID is included in the identifier so that the model can be referenced with version accuracy.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The (version accurate) Used parameter identifier attribute is essential information needed to facilitate automated traceability to the used parameter.

==== 2.6.9 Used parameter URL

Attribute description:: The Used parameter URL is a alternate way to identify the used parameter. All information given to the used parameter identifier attribute apply here.
Obligation and Level:: L2 Opt.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: All of the information given for the Used parameter identifier attribute applies here as well.

==== 2.6.10 Used parameter full name

Attribute description:: The Parameter full name is a descriptive name for the used parameter.
Obligation and Level:: L2 Opt.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Used parameter full name attribute helps quickly recognize and understand the meaning of a used parameter.

==== 2.6.11 Used test case name

Attribute description:: The Used test case name is the given name of a test case actually used in simulation execution.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The combination of Used test case name and Used test case version shall be unique.

==== 2.6.12 Used test case version

Attribute description:: The Used test case version is the given version identifier of a test case actually used in simulation execution.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The combination of Used test case name and Used test case version shall be unique.

==== 2.6.13 Used test case identifier

Attribute description:: The Used test case identifier is the unique master ID of the used test case within the company's project management IT infrastructure. If the company has a versioning mechanism for test cases in project management IT infrastructure, the version ID is included in the identifier so that the model can be referenced with version accuracy.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The (version accurate) Used test case identifier attribute is essential information needed to facilitate automated traceability to the used test case.

==== 2.6.14 Used test case URL

Attribute description:: The Used test case URL is a alternate way to identify the used test case. All information given to the used test case identifier attribute apply here.
Obligation and Level:: L2 Opt.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: All of the information given for the Used test case identifier attribute applies here as well.

==== 2.6.15 Used test case full name

Attribute description:: The Used test case full name is a descriptive name for the used test case.
Obligation and Level:: L2 Opt.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Providing the Used test case full name attribute helps quickly recognize and understand the meaning of a used test case.

==== 2.6.16 Used tool name

Attribute description:: The Used tool name is the given name of a tool actually used in simulation execution.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The combination of Used tool name and Used tool version shall be unique.

==== 2.6.17 Used tool version

Attribute description:: The Used tool version is the given version identifier of a tool actually used in simulation execution.
Obligation and Level:: L2 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The combination of Used tool name and Used tool version shall be unique.

==== 2.6.18 Used tool settings

Attribute description:: The Used tool settings is a tool specific setting actually applied to in simulation execution.
Obligation and Level:: L3 Rec.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: The Tool settings are very similar to parameters. They can also consist of a parameter and a parameter value. However, tool settings are not applied to models but to tools. They must therefore be compatible with the used tool if they are applied in simulation execution.

==== 2.6.19 Execution log

Attribute description:: The Execution log records all relevant activities within the simulation environment chronologically and usually saves them in a simple text file with the date and time, sometimes even in millisecond intervals.
Obligation and Level:: L4 Opt.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: The Execution log is usually consulted if the technical execution of a simulation is not running smoothly or if there are even errors or process aborts.

=== 2.7 Evaluation

==== 2.7.1 Evaluation results

Attribute description:: The Evaluation results are the key results that emerges from the processing of the raw results.
Obligation and Level:: L1 Man.
Can have multiple values:: Yes
Value examples:: 
Additional explanation and rationale:: Typically the attribute Evaluation results contains a link to the result data files.

==== 2.7.2 Evaluation quality-assurance results

Attribute description:: The Implementation quality assurance results describe the outcome of quality measurements done.
Obligation and Level:: L3 Rec.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: Providing the  Implementation quality assurance results attribute helps to recognize and understand the base of the implementation quality verdict.  This attribute can contain a link to the results or quality assurance report.

==== 2.7.3 Evaluation quality verdict

Attribute description:: The Evaluation quality verdict the the result of the evaluation of the simulation results. i.e. whether the simulation results could be considered valid and can appropriately meet the simulation objectives.
Obligation and Level:: L4 Opt.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: Providing the Evaluation quality verdict attribute helps to recognize the quality status of the simulation results.  This attribute can contain a link to a signed quality assurance protocol.

=== 2.8 Fulfillment

==== 2.8.1 Objectives fulfilled

Attribute description:: The Objective fulfilled attribute is the clear and unambiguous documentation of a objective fulfillment decision with a predefined set of applicable entries, that indicates whether the objectives linked with the simulation task are fulfilled or not or whether a statement of the objectives fulfillment ist not possible.
Obligation and Level:: L1 Man.
Can have multiple values:: No
Value examples:: Yes: Objectives are fulfilled No; Objectives are not fulfilled No statement possible
Additional explanation and rationale:: The Objective fulfillment attribute helps quickly recognize and assess the simulation results without having to inspect all the details of a simulation task.

==== 2.8.2 Credibility fulfilled

Attribute description:: The Credibility fulfilled attribute is the clear and unambiguous documentation of a credibility fulfillment decision with a predefined set of applicable entries, that indicates whether the simulation task fulfills credibility requirements or not or whether a statement of the credibility fulfillment ist not possible.
Obligation and Level:: L1 Man.
Can have multiple values:: No
Value examples:: Yes: Credibility sufficient. Statements about objectives are possible No; Credibility not sufficient e.g. tolerances of sim results, confidence intervals do not allow statements about objectives No statement possible: No specifications for credibility or no evaluation carried out
Additional explanation and rationale:: The Credibility fulfillment attribute helps quickly recognize and assess the simulation credibility without having to inspect all the details of a simulation task.

==== 2.8.3 Task fulfilled

Attribute description:: The Task fulfilled attribute is the final assessment of the entire simulation task. The attribute comprises the combination and conclusion from the assessment of objective fulfillment and the assessment of credibility fulfillment.
Obligation and Level:: L1 Man.
Can have multiple values:: No
Value examples:: Yes: Statements about credibility, objectives are possible No; Canceled, so no statements about credibility, objectives possible In Progress: In progress
Additional explanation and rationale:: The Task fulfilled attribute helps quickly recognize and assess the simulation task fulfillment without having to inspect all the details of a simulation task.

==== 2.8.4 Fulfillment evidence

Attribute description:: The Fulfillment evidence attribute links a more detailed report documenting the objective, credibility and task fulfillment assessment and decision.
Obligation and Level:: L3 Rec.
Can have multiple values:: No
Value examples:: 
Additional explanation and rationale:: The Fulfillment evidence attribute helps learn more about the evidence of the task fulfillment decision without having to inspect to much details behind the decision.

